test_1 = {
	
	'BMI'
	'Side'
	'Gender'
	'AGE_AT_ADMIT'
	'PreOpNarcotic'
	'PreOpDMMeds'
	'PreOpInsulin'
	'PreOpBloodThinner'
	'RawDx'
	'PreOpHgb'
    'PreOpCr'
    'PreOpALC'
    'PreOpGlucose'
    'arrhythmias'
    'valvular'
    'pulm circ'
    'PVD'
    'HTNw/oCx'
    'HTNw/Cx'
    'Paralysis'
    'other neuro'
    'chronic pulm'
    'DMw/oCx'
    'DMw/Cx'
    'hypothyroid'
    'renal failure'
    'liver failure'
    'PUD'
    'AIDS'
    'L0oma'
    'Mets'
    'solidCaw/oMets'
    'RA/CVD'
    'coagulopathy'
    'obesity'
    'weightLoss'
    'fluidElectrolyte'
    'bloodLossAnemia'
    'DeficiencyAnemia'
    'EtOH'
    'Drugs'
    'Psychosis'
    'Depression'
